[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
lexer = { path = "../lexer" }
ir = { path = "../ir" }
smallvec = { version = "1.15.1", features = ["union"] }
